/* AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
   Generated by scripts/generateLessons.ts
*/
export type LessonPhrase = { id: string; texts: Record<string, string> };
export type Lesson = { id: string; title: string; description: string; phrases: LessonPhrase[] };

export const LESSONS: Lesson[] = [
  {
    "id": "introductions",
    "title": "Introductions",
    "description": "Simple ways to say who you are and ask about the other person.",
    "phrases": [
      {
        "id": "intro-1",
        "texts": {
          "en-US": "Hi, my name is Chad.",
          "pt-BR": "Oi, meu nome é Chad.",
          "es-ES": "Hola, me llamo Chad.",
          "es-MX": "Hola, me llamo Chad.",
          "fr-FR": "Salut, je m'appelle Chad.",
          "de-DE": "Hallo, ich heiße Chad.",
          "it-IT": "Ciao, mi chiamo Chad."
        }
      },
      {
        "id": "intro-2",
        "texts": {
          "en-US": "Nice to meet you.",
          "pt-BR": "Prazer em te conhecer.",
          "es-ES": "Encantado de conocerte.",
          "es-MX": "Encantado de conocerte.",
          "fr-FR": "Enchanté de vous rencontrer.",
          "de-DE": "Schön, dich kennenzulernen.",
          "it-IT": "Piacere di conoscerti."
        }
      },
      {
        "id": "intro-3",
        "texts": {
          "en-US": "Where are you from?",
          "pt-BR": "De onde você é?",
          "es-ES": "¿De dónde eres?",
          "es-MX": "¿De dónde eres?",
          "fr-FR": "D'où viens-tu?",
          "de-DE": "Woher kommst du?",
          "it-IT": "Da dove vieni?"
        }
      }
    ]
  },
  {
    "id": "travel-basics",
    "title": "Travel – basics",
    "description": "Useful phrases for getting around and asking for help.",
    "phrases": [
      {
        "id": "travel-1",
        "texts": {
          "en-US": "Excuse me, where is the bathroom?",
          "pt-BR": "Com licença, onde fica o banheiro?",
          "es-ES": "Disculpe, ¿dónde está el baño?",
          "es-MX": "Disculpe, ¿dónde está el baño?",
          "fr-FR": "Excusez-moi, où sont les toilettes?",
          "de-DE": "Entschuldigung, wo ist die Toilette?",
          "it-IT": "Scusi, dove si trova il bagno?"
        }
      },
      {
        "id": "travel-2",
        "texts": {
          "en-US": "How much does this cost?",
          "pt-BR": "Quanto custa isso?",
          "es-ES": "¿Cuánto cuesta esto?",
          "es-MX": "¿Cuánto cuesta esto?",
          "fr-FR": "Combien ça coûte?",
          "de-DE": "Wie viel kostet das?",
          "it-IT": "Quanto costa questo?"
        }
      },
      {
        "id": "travel-3",
        "texts": {
          "en-US": "Can you help me, please?",
          "pt-BR": "Você pode me ajudar, por favor?",
          "es-ES": "¿Puedes ayudarme, por favor?",
          "es-MX": "¿Puedes ayudarme, por favor?",
          "fr-FR": "Pouvez-vous m'aider, s'il vous plaît?",
          "de-DE": "Können Sie mir bitte helfen?",
          "it-IT": "Puoi aiutarmi, per favore?"
        }
      }
    ]
  }
] as const;
